@extends('layouts.dashboard')

@section('content')
    <div class="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="mb-2 text-sm font-medium text-[#668277]">Catalogo</p><h2 class="font-display text-3xl font-bold tracking-tight">Productos</h2><p class="mt-2 text-sm text-[#6d8077]">Administra precios, stock y categorias.</p></div><button type="button" onclick="document.getElementById('product-form').classList.toggle('hidden')" class="rounded-xl bg-[#10251e] px-4 py-3 text-sm font-semibold text-white">+ Nuevo producto</button></div>
    @if (session('success'))<p class="mb-5 rounded-xl bg-[#edf7e8] px-4 py-3 text-sm font-semibold text-[#4b7a35]">{{ session('success') }}</p>@endif
    <form id="product-form" method="POST" action="{{ route('productos.store') }}" class="mb-6 hidden grid gap-4 rounded-2xl border border-[#dce5df] bg-white p-5 sm:grid-cols-4">@csrf<input name="name" required placeholder="Producto" class="rounded-xl border border-[#dce5df] px-3 py-2.5 text-sm"><select name="category_id" class="rounded-xl border border-[#dce5df] px-3 py-2.5 text-sm"><option value="">Categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input name="price" type="number" step="0.01" min="0" required placeholder="Precio" class="rounded-xl border border-[#dce5df] px-3 py-2.5 text-sm"><input name="stock" type="number" min="0" required placeholder="Stock" class="rounded-xl border border-[#dce5df] px-3 py-2.5 text-sm"><button class="rounded-xl bg-[#52752b] px-4 py-2.5 text-sm font-semibold text-white sm:col-span-4">Guardar producto</button></form>
    <section class="overflow-hidden rounded-2xl border border-[#dce5df] bg-white shadow-sm"><div class="border-b border-[#edf1ee] p-5"><span class="text-sm text-[#789086]">{{ $products->count() }} productos registrados</span></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-[#f8faf9] text-xs uppercase tracking-wider text-[#789086]"><tr><th class="px-5 py-4">Producto</th><th class="px-5 py-4">Categoria</th><th class="px-5 py-4">Precio</th><th class="px-5 py-4">Stock</th><th class="px-5 py-4">Estado</th><th class="px-5 py-4">Acciones</th></tr></thead><tbody class="divide-y divide-[#edf1ee]">@forelse($products as $product)<tr><form method="POST" action="{{ route('productos.update', $product) }}">@csrf @method('PATCH')<td class="px-5 py-4"><input name="name" value="{{ $product->name }}" class="w-48 rounded-lg border border-transparent px-2 py-1 font-semibold"></td><td class="px-5 py-4"><select name="category_id" class="rounded-lg border border-transparent px-2 py-1 text-[#6d8077]"><option value="">Sin categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($product->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></td><td class="px-5 py-4"><input name="price" type="number" step="0.01" value="{{ $product->price }}" class="w-28 rounded-lg border border-transparent px-2 py-1"></td><td class="px-5 py-4"><input name="stock" type="number" min="0" value="{{ $product->stock }}" class="w-20 rounded-lg border border-transparent px-2 py-1"></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $product->active ? 'bg-[#edf7e8] text-[#4b7a35]' : 'bg-[#f1f1f1] text-[#777]' }}">{{ $product->active ? 'Activo' : 'Inactivo' }}</span></td><td class="px-5 py-4"><button class="mr-2 text-xs font-semibold text-[#52752b]">Guardar</button></form><form class="inline" method="POST" action="{{ route('productos.toggle', $product) }}">@csrf @method('PATCH')<button class="text-xs font-semibold text-[#a06a2e]">{{ $product->active ? 'Inactivar' : 'Activar' }}</button></form></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-sm text-[#789086]">No hay productos. Crea el primero.</td></tr>@endforelse</tbody></table></div></section>
    @if (auth()->user()->role?->name === 'Administrador')
        <section class="mt-6 overflow-hidden rounded-2xl border border-[#dce5df] bg-white shadow-sm"><div class="border-b border-[#edf1ee] p-5"><h3 class="font-display text-lg font-bold">Categorias</h3><p class="mt-1 text-sm text-[#789086]">Administradas desde el panel del administrador.</p></div><form method="POST" action="{{ route('categories.store') }}" class="grid gap-3 border-b border-[#edf1ee] p-5 sm:grid-cols-[1fr_auto]">@csrf<input name="name" required placeholder="Nueva categoria" class="rounded-xl border border-[#dce5df] px-3 py-2.5 text-sm"><button class="rounded-xl bg-[#52752b] px-4 py-2.5 text-sm font-semibold text-white">Crear categoria</button></form><div class="divide-y divide-[#edf1ee]">@foreach($allCategories as $category)<div class="flex items-center justify-between gap-4 p-5"><form method="POST" action="{{ route('categories.update', $category) }}" class="flex flex-1 gap-3">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" class="w-full max-w-sm rounded-lg border border-transparent px-2 py-1 font-semibold"><button class="text-xs font-semibold text-[#52752b]">Guardar</button></form><form method="POST" action="{{ route('categories.toggle', $category) }}">@csrf @method('PATCH')<button class="text-xs font-semibold text-[#a06a2e]">{{ $category->active ? 'Inactivar' : 'Activar' }}</button></form></div>@endforeach</div></section>
    @endif
@endsection
